FROM ubuntu:18.04

RUN apt update && \
    apt install -y python3 python3-dev python3-pip wget unzip libxml2-dev libxmlsec1-dev libldap2-dev libssl-dev gcc \
    libsasl2-dev postgresql-client


COPY ./dev_files/odoo_requirements.txt /odoo_requirements.txt
COPY ./requirements/requirements.txt /requirements.txt

RUN pip3 install -U pip  && \
    pip3 install -r /odoo_requirements.txt --no-cache-dir && \
    pip3 install -r  /requirements.txt --no-cache-dir

RUN pip3 install vcrpy-unittest

COPY ./ /app

WORKDIR /app

ENTRYPOINT sh ./dev_files/entrypoint_dev.sh
